version: '3.9'

services:
  btracker_database:
    image: postgres:13.0-alpine
    env_file:
      - ./database/.env
    container_name: tdatabase
    ports:
      - 5432:5432
    networks:
      - bst_network
    volumes:
      - ./database/volume:/var/lib/postgresql/data:rw
  
networks:
  bst_network:
    driver: bridge

  