services:
  btracker_database:
    image: postgres:13.0-alpine
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    container_name: btracker_database
    networks:
      - btracker_network
    volumes:
      - ./database/data:/var/lib/postgresql/data:rw
  
  btracker_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    expose:
      - 8000
    container_name: btracker_backend
    networks:
      - btracker_network
    depends_on:
      - btracker_database
    links:
      - btracker_database:btracker_database

networks:
  btracker_network:
    driver: bridge

