version: '3.9'

services:
  btracker_database:
    image: postgres:13.0-alpine
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    container_name: btracker_database
    networks:
      - btracker_network
    volumes:
      - ./database/data:/var/lib/postgresql/data:rw

networks:
  btracker_network:
    driver: bridge

