services:
  btracker_database:
    image: postgres:13.0-alpine
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    container_name: btr_database
    networks:
      - btracker_network
    volumes:
      - ./database/data:/var/lib/postgresql/data:rw
  
  btracker_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    expose:
      - 8000
    container_name: btr_backend
    networks:
      - btracker_network
    depends_on:
      - btracker_database

  btracker_fronted:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "80:3000"
    expose:
      - 80
    container_name: btr_frontend
    networks:
      - btracker_network
    depends_on:
      - btracker_backend

networks:
  btracker_network:
    driver: bridge

