# Generated by Django 5.1.1 on 2024-09-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='created_at',
            new_name='update_at',
        ),
    ]
