# Generated by Django 5.1.1 on 2024-09-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='current_latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='bus',
            name='current_longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
