# Generated by Django 5.1.1 on 2024-10-08 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_bus_current_latitude_bus_current_longitude'),
        ('route', '0003_remove_stop_route_remove_stop_station_stop_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='current_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='route_bus', to='route.route'),
        ),
    ]
