# Generated by Django 5.1.1 on 2024-10-08 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_route_status_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='route',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='station',
        ),
        migrations.AddField(
            model_name='stop',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='stop',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.stop')),
            ],
        ),
    ]
