# Generated by Django 5.1.1 on 2024-10-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_remove_stop_route_remove_stop_station_stop_latitude_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'stop')},
        ),
    ]
