name: build docker images

on:
  push:
    branches:
      - main

jobs:
  ## Continuous integration
  ci-backend:
    runs-on: ubuntu-latest
    container:
      image: python
    
    services:
      tdatabase:
        image: postgres:13.0-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    steps:
      - uses: actions/checkout@v1
      - name: Install backend deps
        working-directory: ./backend
        run:  |
          apt-get install python3-dev
          python -m pip install --upgrade pip
          pip install -r requirements/integration.txt
          python manage.py makemigrations
          python manage.py migrate
          python manage.py migrate --run-syncdb
      
      - name: Run backend tests
        working-directory: ./backend
        run:
          python -m pytest

  ## Continuous delivery
  cd-backend:
    runs-on: ubuntu-latest
    needs: ci-backend
    steps:
      - name: Docker build and tag image
        working-directory: ./backend
        run: docker build -t bs_tracker-bs_backend .