name: build docker images

on:
  push:
    branches:
      - main

jobs:
  ## Continuous integration
  ci-backend:
    runs-on: ubuntu-latest
    container:
      image: python
    
    services:
      tdatabase:
        image: postgres:13.0-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/common.txt
      # - name: Run backend tests
      #   working-directory: ./backend
      #   run:
      #     python -m pytest

  ## Continuous delivery
  cd-backend:
    runs-on: ubuntu-latest
    needs: ci-backend
    steps:
      - uses: actions/checkout@v1
      - name: Docker build and tag image
        working-directory: ./backend
        run: |
          docker build . -t bs_tracker-bs_backend
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: push image version to hub
        run:
          docker push ${{ secrets.DOCKER_USER }}/bs_backend:${{ github.sha }}
      - name: Docker TAG latest images
        run:
            docker tag docker.io/bs_backend ${{ secrets.DOCKER_USER }}/bs_backend:latest
      - name: push image to hub
        run:
            docker push ${{ secrets.DOCKER_USER }}/bs_backend:latest